version: '3.8'

services:
  rest:
    build:
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    # ограничение CPU для быстрого достижения потолка
    deploy:
      resources:
        limits:
          cpus: '0.5'

  grpc:
    build:
      context: ./service2
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    deploy:
      resources:
        limits:
          cpus: '0.5'