version: '3.9'

services:
  app:
    build: service1/
    image: tickets-svc-s04
    container_name: tickets-app
    ports:
      - "8195:8195"  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8195/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
    networks:
      - app-net
    depends_on:
      redis:
        condition: service_healthy  

  redis:
    image: redis:7-alpine
    container_name: tickets-redis
    ports:
      - "6379:6379"
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes  
    volumes:
      - redis_data:/data  

  gateway:
    image: nginx:1.25-alpine
    container_name: tickets-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app:
        condition: service_healthy  
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
    name: tickets-network

volumes:
  redis_data: