services:
  user-service:
    build: ./user-service
    ports: ["8001:8000"]
 
    depends_on:
      postgres-users: {condition: service_healthy}
    networks: [backend]

  order-service:
    build: ./order-service
    ports: ["8002:8000"]
   
    depends_on:
      postgres-orders: {condition: service_healthy}
      rabbitmq: {condition: service_healthy}
      notification-service: {condition: service_started}
    networks: [backend]

  notification-service:
    build: ./notification-service
    ports: ["8003:8000", "50051:50051"]
    depends_on:
      postgres-notif: {condition: service_healthy}
      rabbitmq: {condition: service_healthy}
    networks: [backend]

  postgres-users:
    image: postgres:16-alpine
    environment: {POSTGRES_USER: auth, POSTGRES_PASSWORD: secret, POSTGRES_DB: users_db}
    volumes: [pg-users:/var/lib/postgresql/data]
    healthcheck: {test: ["CMD-SHELL", "pg_isready -U auth"], interval: 5s, retries: 5}
    networks: [backend]

  postgres-orders:
    image: postgres:16-alpine
    environment: {POSTGRES_USER: orders, POSTGRES_PASSWORD: secret, POSTGRES_DB: orders_db}
    volumes: [pg-orders:/var/lib/postgresql/data]
    healthcheck: {test: ["CMD-SHELL", "pg_isready -U orders"], interval: 5s, retries: 5}
    networks: [backend]

  postgres-notif:
    image: postgres:16-alpine
    environment: {POSTGRES_USER: notif, POSTGRES_PASSWORD: secret, POSTGRES_DB: notif_db}
    volumes: [pg-notif:/var/lib/postgresql/data]
    healthcheck: {test: ["CMD-SHELL", "pg_isready -U notif"], interval: 5s, retries: 5}
    networks: [backend]

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports: ["5672:5672", "15672:15672"]
    environment: {RABBITMQ_DEFAULT_USER: guest, RABBITMQ_DEFAULT_PASS: guest}
    healthcheck: {test: ["CMD-SHELL", "rabbitmq-diagnostics check_port_connectivity"], interval: 10s, retries: 5}
    networks: [backend]

  nginx:
    image: nginx:1.25
    ports: ["80:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      user-service: {condition: service_started}
      order-service: {condition: service_started}
      notification-service: {condition: service_started}
    networks: [backend]

networks:
  backend: {driver: bridge}
volumes:
  pg-users:
  pg-orders:
  pg-notif: