# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x08users.v1\"%\n\x05query\x12\r\n\x05users\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"-\n\x08mutation\x12\x12\n\ncreateUser\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t2o\n\x0cUsersService\x12)\n\x05Users\x12\x0f.users.v1.query\x1a\x0f.users.v1.query\x12\x34\n\nCreateUser\x12\x12.users.v1.mutation\x1a\x12.users.v1.mutationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERY']._serialized_start=27
  _globals['_QUERY']._serialized_end=64
  _globals['_MUTATION']._serialized_start=66
  _globals['_MUTATION']._serialized_end=111
  _globals['_USERSSERVICE']._serialized_start=113
  _globals['_USERSSERVICE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
